"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BOTH_SIDE = exports.KING_SIDE = exports.QUEEN_SIDE = exports.rowNotation = exports.columnNotation = exports.WHITE = exports.BLACK = exports.EMPTY = exports.ROOK = exports.QUEEN = exports.KING = exports.kNIGHT = exports.BISHOP = exports.PAWN = void 0;
exports.PAWN = 'PAWN';
exports.BISHOP = 'BISHOP';
exports.kNIGHT = 'KNIGHT';
exports.KING = 'KING';
exports.QUEEN = 'QUEEN';
exports.ROOK = 'ROOK';
exports.EMPTY = 'EMPTY';
exports.BLACK = 'BLACK';
exports.WHITE = 'WHITE';
exports.columnNotation = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'];
exports.rowNotation = ['8', '7', '6', '5', '4', '3', '2', '1'];
exports.QUEEN_SIDE = 'QUEEN_SIDE';
exports.KING_SIDE = 'KING_SIDE';
exports.BOTH_SIDE = 'BOTH_SIDE';
