"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LEAVE_GAME_EVENT = exports.OFFER_DRAW_EVENT = exports.STEAL_MATE_EVENT = exports.CHECK_MATE_EVENT = exports.TIME_OUT_EVENT = exports.RESIGN_EVENT = exports.ACCEPT_REMATCH_EVENT = exports.ASK_REMATCH_EVENT = exports.JOIN_GAME_EVENT = exports.NEW_GAME_READY_EVENT = exports.CASTLE_KING_EVENT = exports.PAWN_PROMOTION_EVENT = exports.MOVE_EVENT = exports.GAME_END_EVENT = exports.GAME_NOT_AVAILABLE_EVENT = exports.GAME_START_EVENT = exports.NEW_CONNECTION_EVENT = exports.NEW_INCOMING_MATCH_REQUEST_EVENT = exports.NEW_CONNECTION_REQUEST_EVENT = exports.OUTGOING_MATCH_REQUEST_DECLINED_EVENT = exports.CONNECTION_UPDATE_EVENT = exports.SESSION_EVENT = void 0;
exports.SESSION_EVENT = 'SESSION_EVENT';
exports.CONNECTION_UPDATE_EVENT = 'CONNECTION_UPDATE_EVENT';
// export const request_game_cancled = 'request_game_cancled';
exports.OUTGOING_MATCH_REQUEST_DECLINED_EVENT = 'OUTGOING_MATCH_REQUEST_DECLINED_EVENT';
exports.NEW_CONNECTION_REQUEST_EVENT = 'NEW_CONNECTION_REQUEST_EVENT';
exports.NEW_INCOMING_MATCH_REQUEST_EVENT = 'NEW_INCOMING_MATCH_REQUEST_EVENT';
exports.NEW_CONNECTION_EVENT = 'NEW_CONNECTION_EVENT';
// ---------------------------------------------------
exports.GAME_START_EVENT = 'GAME_START_EVENT';
exports.GAME_NOT_AVAILABLE_EVENT = 'GAME_NOT_AVAILABLE_EVENT';
exports.GAME_END_EVENT = 'GAME_END_EVENT';
exports.MOVE_EVENT = 'MOVE_EVENT';
exports.PAWN_PROMOTION_EVENT = 'PAWN_PROMOTION_EVENT';
exports.CASTLE_KING_EVENT = 'CASTLE_KING_EVENT';
exports.NEW_GAME_READY_EVENT = 'NEW_GAME_READY_EVENT';
/*
 Emitted By client
*/
exports.JOIN_GAME_EVENT = 'JOIN_GAME_EVENT';
exports.ASK_REMATCH_EVENT = 'ASK_REMATCH_EVENT';
exports.ACCEPT_REMATCH_EVENT = 'ACCEPT_REMATCH_EVENT';
exports.RESIGN_EVENT = 'RESIGN_EVENT';
exports.TIME_OUT_EVENT = 'TIME_OUT_EVENT';
exports.CHECK_MATE_EVENT = 'CHECK_MATE_EVENT';
exports.STEAL_MATE_EVENT = 'STEAL_MATE_EVENT';
exports.OFFER_DRAW_EVENT = 'OFFER_DRAW_EVENT';
exports.LEAVE_GAME_EVENT = 'LEAVE_GAME_EVENT';
