export const SESSION_EVENT = 'SESSION_EVENT';
export const CONNECTION_UPDATE_EVENT = 'CONNECTION_UPDATE_EVENT';
// export const request_game_cancled = 'request_game_cancled';
export const OUTGOING_MATCH_REQUEST_DECLINED_EVENT = 'OUTGOING_MATCH_REQUEST_DECLINED_EVENT';
export const NEW_CONNECTION_REQUEST_EVENT = 'NEW_CONNECTION_REQUEST_EVENT';
export const NEW_INCOMING_MATCH_REQUEST_EVENT = 'NEW_INCOMING_MATCH_REQUEST_EVENT';
export const NEW_CONNECTION_EVENT = 'NEW_CONNECTION_EVENT';
// ---------------------------------------------------
export const GAME_START_EVENT = 'GAME_START_EVENT';
export const GAME_NOT_AVAILABLE_EVENT = 'GAME_NOT_AVAILABLE_EVENT';
export const GAME_END_EVENT = 'GAME_END_EVENT';
export const MOVE_EVENT = 'MOVE_EVENT';
export const PAWN_PROMOTION_EVENT = 'PAWN_PROMOTION_EVENT';
export const CASTLE_KING_EVENT = 'CASTLE_KING_EVENT';
export const NEW_GAME_READY_EVENT = 'NEW_GAME_READY_EVENT';
/*
 Emitted By client
*/
export const JOIN_GAME_EVENT = 'JOIN_GAME_EVENT';
export const ASK_REMATCH_EVENT = 'ASK_REMATCH_EVENT';
export const ACCEPT_REMATCH_EVENT = 'ACCEPT_REMATCH_EVENT';
export const RESIGN_EVENT = 'RESIGN_EVENT';
export const TIME_OUT_EVENT = 'TIME_OUT_EVENT';
export const CHECK_MATE_EVENT = 'CHECK_MATE_EVENT';
export const STEAL_MATE_EVENT = 'STEAL_MATE_EVENT';
export const OFFER_DRAW_EVENT = 'OFFER_DRAW_EVENT';
export const LEAVE_GAME_EVENT = 'LEAVE_GAME_EVENT';
