export const SETUP_BOARD = 'SETUP_BOARD';
export const GAME_NOT_AVAILABLE = 'GAME_NOT_AVAILABLE'

export const SELECT_PIECE = 'SELECT_PIECE';

export const MOVE_PIECE = 'MOVE_PIECE';
export const OPPONENT_MOVE_PIECE = 'OPPONENT_MOVE_PIECE';

export const PAWN_PROMOTION = 'PAWN_PROMOTION'
export const OPPONENT_PAWN_PROMOTION = 'OPPONENT_PAWN_PROMOTION';

export const CASTLING_KING = 'CASTLING_KING';
export const OPPONENT_CASTLING_KING = 'OPPONENT_CASTLING_KING';

export const INITIALISE_CONTEXT = 'INITIALISE_CONTEXT'

export const HIGHLIGHTED_SQUARE = 'HIGHLIGHTED_SQUARE';
export const SWITCH_TURN = 'SWITCH_TURN';
export const RESIGN_GAME = 'RESIGN_GAME';
export const GAME_END = 'GAME_END';