export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const MUST_SIGNUP = "MUST_SIGNUP";
export const MUST_LOGIN = "MUST_LOGIN";
export const LOGOUT = "LOGOUT";
export const ERROR = "ERROR";
export const LOADING = "LOADING";
export const DONE = "DONE";

export const SESSION_SUCCESS = 'SESSION_SUCCESS';

export const SET_CONNECTED_FRIEND = 'SET_CONNECTED_FRIEND';
export const SET_CONNECTIONS_REQUEST = 'SET_CONNECTIONS_REQUEST'
export const SET_USER_GAME_INVITATIONS = 'SET_USER_GAME_INVITATIONS';
export const SET_USER_GAME_REQUEST = 'SET_USER_GAME_REQUEST';

export const FRIEND_STATUS_CHANGED = 'FRIEND_STATUS_CHANGED';

export const REQUEST_CONNECTION_SUCCESS = 'REQUEST_CONNECTION_SUCCESS';
export const ADD_NEW_REQUEST_CONNECTION = 'ADD_NEW_REQUEST_CONNECTION';
export const ADD_NEW_FRIEND = 'ADD_NEW_FRIEND';
export const REMOVE_USER_GAME_REQUEST = 'REMOVE_USER_GAME_REQUEST'

export const USER_GAME_REQUEST_SUCCESS = 'USER_GAME_REQUEST_SUCCESS';
export const ADD_NEW_USER_GAME_INVITATION = 'ADD_NEW_USER_GAME_INVITATION'
export const REMOVE_USER_GAME_INVITATION = 'REMOVE_USER_GAME_INVITATION' 
export const USER_GAME_REQUEST_CANCLED = 'USER_GAME_REQUEST_CANCLED';

export const NEW_GAME_READY = 'NEW_GAME_READY';

export const CLEAR_TAB_NOTIFICATION = 'CLEAR_TAB_NOTIFICATION'

